added globalEvents flags json and documentation md file
helldivers-2/json pull request #45
Opened 2024-06-05 11:28 UTC by DetKewlDog

Figured this out using @jgaribsin 's `globalEvents` historical dump a while ago but I've noticed it's still not in this repo. Thought I might as well add it myself :)

```json
// status endpoint
{
  // ...
  "globalEvents": [
    {
      "eventId": 1499087,
      "id32": 0,
      "portraitId32": 0,
      "title": "BRIEFING",
      "titleId32": 2908633975,
      "message": "...",
      "messageId32": 46181626,
      "race": 1,
      "flag": 1, // <-- This is the flag value i documented
      "assignmentId32": 2311178494,
      "effectIds": [],
      "planetIndices": []
    }
  ],
  // ...
}
```

2024-06-05 21:19 UTC, chatterchats commented
Please modify jrd.tree to include the update file. I also recommend adding pages to your fork repo to test your changes to the documentation

2024-06-06 06:56 UTC, dealloc requested changes

2024-06-06 06:56 UTC, dealloc commented on .github/workflows/blank.yml
I'm not entirely a fan of the name 'blank' for the workflow file, not particularly descriptive.

2024-06-06 06:56 UTC, dealloc commented on Writerside/topics/globalEvents_flags.md
> +This json contains a dictionary of key: value pairs, representing the globalEvent flag (which correlates to its type) returned from the Helldivers 2 Status API endpoint.
```suggestion
This json contains a dictionary of key/value pairs, representing the `globalEvent` flag returned from the Helldivers 2 Status API endpoint.
```

2024-06-06 06:56 UTC, dealloc commented on Writerside/topics/globalEvents_flags.md
> +```json
I would avoid copying the contents of `globalEvents_flags` here as any update to that file would also need to be made here.
Preferably link to the file itself to make maintenance easier

2024-06-06 06:56 UTC, dealloc commented on Writerside/topics/globalEvents_flags.md
Overall documentation could use work, it reads a little choppy still.
Try moving away from the 'dictionary' style of documentation and describe what global events are, point out which property indicates the global event, and in the example I'm missing what JSON you're showing (is this a planet, dispatch, ...)

2024-06-06 07:12 UTC, DetKewlDog commented on .github/workflows/blank.yml
Yeah i was trying to figure out gh pages, I'll delete it

2024-07-08 15:32 UTC, dmpaskell22 commented on Writerside/topics/globalEvents_flags.md
> +	"2": "Briefing",
wh673-256.62
USD

2024-08-06 21:34 UTC, closed without merging

2024-08-07 18:31 UTC, dealloc commented
@DetKewlDog how comes we closed this PR?
some small changes and I feel this could've been ready to merge

2024-08-07 18:32 UTC, DetKewlDog commented
Couldn't find the time to work on it and I didn't want it to stay open for no reason :(