Galactic effects & correcting new planet enviornmental effects
helldivers-2/json pull request #71
Opened 2024-11-15 21:15 UTC by CrosswaveOmega

This Pull Request contains the known effects of all observed Active Planet Effects, switches biome keys to the internal game names for the sake of consistency, and corrections for the temperature alternating planets.

2024-11-15 21:22 UTC, lambstream commented on effects/planetEffects.json
Please use the .editorconfig styling

2024-11-15 21:22 UTC, lambstream commented on planets/biomes.json
Please use the .editorconfig styling

2024-11-15 21:23 UTC, lambstream commented on planets/planets.json
Please use the .editorconfig styling

2024-11-15 21:35 UTC, chatterchats commented
Regarding the `planets.json` - While acknowledging that out data is also potentially mistaken, how are you determining which evnironmental effects are on the the planet? For Example, Klen Dath II (planet_001) has both intense heat and extreme cold on your version. (This is in addition to the fact that the only environmental effect it should have is Sandstorm as per the helldiversData repo by Shalzuth)

2024-11-15 21:46 UTC, CrosswaveOmega commented
@chatterchats 
17th september, patch 01.001.100
One of the patches on September 17th internally changed the way the game handles temperature.  It's now specific to the weather settings instead of the environmental effects.  

For example, on Klen Dath II and planets that share it's settings, the extreme heat/cold modifiers is now applied whenever the time in the mission area is day/night respectively.  I built a special script to get this mapped.

2024-11-15 22:21 UTC, lambstream requested changes
Please update the coding style. You're using spaces instead of tabs.

2024-11-15 22:21 UTC, chatterchats commented
> @chatterchats One of the patches on September 17th (patch 01.001.100) internally changed the way the game handles temperature. It's now specific to the weather settings instead of the environmental effects.
> 
> For example, on Klen Dath II and planets that share it's settings, the extreme heat/cold modifiers is now applied whenever the time in the mission area is day/night respectively. I built a special script to get this mapped.

@CrosswaveOmega 
Hm... That change may indicate we need to restructure, since that field has pretty much always correlated to the planet's `gameplay_modifiers`. I'll talk w/ the other folks about this to decide how we want to move forward with that

Just a brief heads-up, the json repo is formatted using 4-width tabs and not spaces, if you could please get that corrected ^^

2024-11-15 22:42 UTC, CrosswaveOmega commented
I am attempting to get the formatting resolved in my editor, hopefully this corrects it.

2024-11-15 22:43 UTC, chatterchats commented
> I am attempting to get the formatting resolved in my editor, hopefully this corrects it.

Looks a lot better!, Thank you

2024-11-28 17:54 UTC, CrosswaveOmega commented on planets/planets.json
> +			"fr-FR": "CHERCHEVOIE\u00a0V",
I think that was an encoding error.

2024-11-28 17:55 UTC, CrosswaveOmega commented on planets/environmentals.json
the EOF should be added now.

2024-11-28 18:03 UTC, CrosswaveOmega commented on planets/biomes.json
Done.

2024-11-29 16:00 UTC, chatterchats approved these changes

2024-11-29 16:04 UTC, dealloc approved these changes

2024-11-29 16:04 UTC, merged